# Generated by Django 4.1.2 on 2022-10-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'default_related_name': 'grupo'},
        ),
    ]
